#!/bin/bash

. util

try make PKGBUILD
try makepkg -f

# Check that LICENSE and manpage are included
try "pacman -Qlp pvpn-*-1-any.pkg.tar.xz | grep -q 'LICENSE$'"
try "pacman -Qlp pvpn-*-1-any.pkg.tar.xz | grep -q 'pvpn.8.gz$'"
