#!/bin/bash

. util

ssh_host="$1"
[[ -z "$ssh_host" ]] && echo "Missing host to test against" >&2 && exit 1

ip_client=10.232.182.1
ip_server=10.232.182.2

# Test ppp tunnel
try sudo ./pvpn -t ppp -i "$ip_client:$ip_server" "$ssh_host"
try "ip route show | grep -q '^$ip_server dev ppp.* src $ip_client'"

# Test ssh-3 tunnel
try sudo ./pvpn -t ssh-3 -i "$ip_client:$ip_server" "$ssh_host"
try "ip route show | grep -q '^$ip_server dev tun.* src $ip_client'"

# Test another ssh-3 tunnel
try sudo ./pvpn -t ssh-3 -i "$ip_client:$ip_server" "$ssh_host"

# Disconnect only ppp tunnel
source /run/pvpn/ppp*
try sudo ./pvpn -S "$client_device"
try "ip route show | grep -qv '^$ip_server dev ppp.* src $ip_client'"
try "ip route show | grep -q  '^$ip_server dev tun.* src $ip_client'"

# Disconnect remaining tunnels
try sudo ./pvpn -S
try "ip route show | grep -qv '^$ip_server dev tun.* src $ip_client'"
